#!/bin/bash

set -e
echo "[INFO]: try to git pull"
git pull
echo "[INFO]: git pulled"

echo "[INFO]: updating Python dependencies"
env/bin/pip3 install -r requirements.txt
echo "[INFO]: Python dependencies updated"

echo "[INFO]: updating JS dependencies"
npm ci --dev
echo "[INFO]: JS dependencies updated"

echo "[INFO]: compile JS"
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
echo "[INFO]: JS compiled"

echo "[INFO]: recollecting static"
env/bin/python3 manage.py collectstatic --noinput
echo "[INFO]: static collected"

echo "[INFO]: making migrations"
env/bin/python3 manage.py makemigrations

echo "[INFO]: applying migrations"
env/bin/python3 manage.py migrate

echo "[INFO]: restarting burger_store_gunicorn.service"
systemctl restart burger_store_gunicorn.service
echo "[INFO]: burger_store_gunicorn.service restarted"

echo "[INFO]: reloading NGINX"
systemctl reload nginx.service
echo "[INFO]: nginx reloaded"
