# Generated by Django 3.2.15 on 2022-10-14 10:02

import os

from hashlib import md5
from random import choice, randint
from django.db import migrations
from django.core.files.base import ContentFile

def add_restaurants(apps, scheme_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    restaurants = [
        {
            'name': '[TEST] Мясо и точка',
            'address': 'Москва Сити',
            'contact_phone': '+74951234567'
        },
        {
            'name': '[TEST] Бургер и точка',
            'address': 'Питер Сити',
            'contact_phone': '+79111234567'
        },
        {
            'name': '[TEST] Бутер и точка',
            'address': 'Казань Сити',
            'contact_phone': '+78431234567'
        }
    ]
    for restaurant in restaurants:
        Restaurant.objects.get_or_create(
            name=restaurant['name'],
            address=restaurant['address'],
            contact_phone=restaurant['contact_phone']
        )

def add_products(apps, scheme_editor):
    Product = apps.get_model('foodcartapp', 'Product')
    ProductCategory = apps.get_model('foodcartapp', 'ProductCategory')
    RestaurantMenuItem = apps.get_model('foodcartapp', 'RestaurantMenuItem')
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')

    restaurants = Restaurant.objects.all()
    prod_cat, _ = ProductCategory.objects.get_or_create(name='burger')
    images = os.listdir('test_images')
    for num, image in enumerate(images):
        
        with open(f'test_images/{image}', 'rb') as image_file:
            
            photo = ContentFile(
                image_file.read(),
                name=md5(image_file.read()).hexdigest()
            )
        product, _ = Product.objects.get_or_create(
            name=f'[TEST] {num}_burger',
            category=prod_cat,
            price=randint(100, 200),
            image=photo,
        )
        RestaurantMenuItem.objects.get_or_create(
            restaurant=choice(restaurants),
            product=product
        )




class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20221014_1000'),
    ]

    operations = [
        migrations.RunPython(add_restaurants),
        migrations.RunPython(add_products)
    ]
