# Generated by Django 3.2.15 on 2022-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20221014_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Заказ в работе'),
        ),
    ]
