# Generated by Django 3.2.15 on 2022-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_is_actual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_actual'], name='foodcartapp_is_actu_9a73fd_idx'),
        ),
    ]
