# Generated by Django 3.2.15 on 2022-10-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20221016_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='current_price',
            field=models.SmallIntegerField(default=0, verbose_name='Стоимость единицы на момент оформления'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_product', to='foodcartapp.order', verbose_name='Заказ'),
        ),
    ]
