# Generated by Django 3.2.15 on 2022-10-27 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20221026_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='price_at_the_order_moment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на время заказа'),
        ),
    ]
