# Generated by Django 3.2.15 on 2022-10-27 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_orderedproduct_price_at_the_order_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='price_at_the_order_moment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оставить пустым, заполняется автоматически', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на время заказа'),
        ),
    ]
