# Generated by Django 3.2.15 on 2022-10-27 08:37

from django.db import migrations


def fix_prices(apps, scheme_editor):
    OrderedProduct = apps.get_model('foodcartapp', 'OrderedProduct')
    ordered_products_no_price = OrderedProduct.objects.filter(
        price_at_the_order_moment=None
    )
    for ordered_product in ordered_products_no_price.iterator():
        ordered_product.price_at_the_order_moment = \
            ordered_product.product.price
        ordered_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.RunPython(fix_prices)
    ]
