# Generated by Django 3.2.15 on 2022-10-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_is_actu_9a73fd_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_actual',
        ),
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает подтверждения'), ('assembly', 'Сборка'), ('delivery', 'Доставляется'), ('complete', 'Выполнен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['completed'], name='foodcartapp_complet_ee9304_idx'),
        ),
    ]
