# Generated by Django 3.2.15 on 2022-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20221027_1110'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_complet_ee9304_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='foodcartapp_status_99d57e_idx'),
        ),
    ]
