# Generated by Django 3.2.15 on 2022-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20221028_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлен'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='foodcartapp_created_cd8d79_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['called_at'], name='foodcartapp_called__a766dd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='foodcartapp_deliver_0afa88_idx'),
        ),
    ]
