# Generated by Django 3.2.15 on 2022-10-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20221028_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн, безнал'), ('upon_delivery', 'На адресе, наличные'), ('clarify', 'Уточнить у клиента')], default='clarify', max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
