# Generated by Django 3.2.15 on 2022-10-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.CharField(choices=[('[TEST] Бургер и точка', '[TEST] Бургер и точка'), ('[TEST] Мясо и точка', '[TEST] Мясо и точка'), ('[TEST] Бутер и точка', '[TEST] Бутер и точка')], default='Выберите ресторан', max_length=50, verbose_name='Исполнитель'),
        ),
    ]
