# Generated by Django 3.2.15 on 2022-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает подтверждения'), ('in_process', 'Готовится'), ('assembly', 'Сборка'), ('delivery', 'Доставляется'), ('complete', 'Выполнен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
