# Generated by Django 3.2.15 on 2022-10-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_order_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.restaurant', verbose_name='Исполнитель'),
        ),
    ]
