# Generated by Django 3.2.15 on 2022-11-03 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_alter_order_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
