# Generated by Django 3.2.15 on 2022-11-03 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_alter_orderedproduct_price_at_the_order_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='price_at_the_order_moment',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на время заказа'),
        ),
    ]
