# Generated by Django 3.2.15 on 2022-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Широта')),
                ('request_date', models.DateTimeField(verbose_name='Дата запроса')),
            ],
        ),
    ]
