# Generated by Django 3.2.15 on 2022-10-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='request_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата запроса'),
        ),
    ]
