# Generated by Django 3.2.15 on 2022-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_management', '0004_auto_20221030_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(max_length=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(max_length=15, null=True, verbose_name='Долгота'),
        ),
    ]
